databases:
  - name: tutor-cerdas-db
    databaseName: saintekmu_db # <-- TAMBAHANNYA DI SINI
    plan: free

services:
  - type: web
    name: tutor-cerdas-saintekmu
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn Tutor_Cerdas_SaintekMu.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tutor-cerdas-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DEBUG
        value: False