# Generated by Django 5.2 on 2025-04-11 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Teks pesan dari pengguna atau chatbot.')),
                ('is_user_message', models.BooleanField(default=True, help_text='True jika pesan dari pengguna, False jika dari chatbot.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Waktu pesan dibuat.')),
                ('user', models.ForeignKey(help_text='Pengguna yang terkait dengan pesan ini.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pesan Chat',
                'verbose_name_plural': 'Pesan Chat',
                'ordering': ['timestamp'],
            },
        ),
    ]
