# Generated by Django 5.2 on 2025-06-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mentorapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorapplication',
            name='other_document',
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='address',
            field=models.TextField(default='', verbose_name='Alamat Domisili'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='mentor_applications/certificates/', verbose_name='Unggah Sertifikat (jika ada)'),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01', verbose_name='Tanggal Lahir'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='declaration',
            field=models.BooleanField(default=False, help_text='Saya menyatakan bahwa data yang saya isi adalah benar dan dapat dipertanggungjawabkan.', verbose_name='Pernyataan Kebenaran Data'),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='education_level',
            field=models.CharField(choices=[('SMA', 'SMA/Sederajat'), ('D3', 'Diploma 3'), ('S1', 'Sarjana (S1)'), ('S2', 'Magister (S2)')], default='', max_length=5, verbose_name='Pendidikan Terakhir'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='gender',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='', max_length=1, verbose_name='Jenis Kelamin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='github_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link GitHub/Portofolio Online'),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='graduation_year',
            field=models.PositiveIntegerField(default=0, verbose_name='Tahun Lulus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='institution_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nama Institusi Pendidikan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='intro_video',
            field=models.FileField(blank=True, help_text='Ukuran maks 50MB', null=True, upload_to='mentor_applications/videos/', verbose_name='Unggah Video Perkenalan (opsional)'),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='major',
            field=models.CharField(default='', max_length=100, verbose_name='Jurusan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='portfolio_pdf',
            field=models.FileField(blank=True, null=True, upload_to='mentor_applications/portfolios/', verbose_name='Unggah Portofolio (PDF)'),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='whatsapp_number',
            field=models.CharField(default='', max_length=20, verbose_name='Nomor WhatsApp Aktif'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='cv',
            field=models.FileField(upload_to='mentor_applications/cvs/', verbose_name='Unggah CV (PDF)'),
        ),
    ]
