# Generated by Django 5.2 on 2025-06-12 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_mentorapplication_other_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorapplication',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='mentor_applications/certificates/', verbose_name='Unggah Sertifikat'),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='declaration',
            field=models.BooleanField(default=False, verbose_name='Pernyataan Kebenaran Data'),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='intro_video',
            field=models.FileField(blank=True, help_text='Opsional, ukuran maks 50MB', null=True, upload_to='mentor_applications/videos/', verbose_name='Unggah Video Perkenalan'),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='whatsapp_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Format nomor WhatsApp tidak valid. Harap gunakan format 628xxxxxx, tanpa spasi atau tanda '+'.", regex='^62\\d{9,15}$')], verbose_name='Nomor WhatsApp Aktif'),
        ),
    ]
