# Generated by Django 5.2 on 2025-06-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_mentorapplication_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Persetujuan'), ('REVIEW', 'Sedang Direview'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=10),
        ),
    ]
