# Generated by Django 5.2 on 2025-06-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_bio_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapplication',
            name='bio',
            field=models.TextField(default='', help_text='Tuliskan perkenalan singkat tentang diri Anda untuk ditampilkan di profil.', max_length=250, verbose_name='Deskripsi Singkat / Bio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='expertise',
            field=models.CharField(default='', help_text='Contoh: Fisika Kuantum, Kalkulus, Pemrograman Python', max_length=100, verbose_name='Bidang Keahlian Utama'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='applicant_pics/', verbose_name='Foto Profil Anda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bidang Keahlian'),
        ),
    ]
