"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url # type: ignore
from pathlib import Path
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'kunci-rahasia-lokal-anda-untuk-development')
# SECRET_KEY = 'django-insecure-=9fh3$%m7c4tf8sqxg2&(g1@&0pwoa!bif%t3!90!sa!r)e%t$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
# DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    
    'core',
    'articles',
    'learning',
    'chatbot',
    'mentor',
    'ckeditor',
    'ckeditor_uploader',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'accounts.apps.AccountsConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.ApplicantStatusMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql', # Gunakan engine PostgreSQL
#        'NAME': 'saintekmu_db',       # GANTI dengan nama database Anda
#        'USER': 'postgres',       # GANTI dengan username database Anda
#        'PASSWORD': '123456',    # GANTI dengan password database Anda
#        'HOST': 'localhost',          # Biasanya 'localhost' jika DB di mesin yang sama
#        'PORT': '5432',               # Port default PostgreSQL (ganti jika beda)
#    }
#}
DATABASES = {
    'default': dj_database_url.config(
        # Ganti nilai default ini dengan URL database lokal Anda jika perlu
        default='postgres://user:password@localhost:5432/nama_db_lokal',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'id'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# config/settings.py
# ... (pengaturan lainnya di atas) ...

# Beri tahu Django untuk menggunakan model User kustom dari aplikasi 'accounts'
AUTH_USER_MODEL = 'accounts.User'

# ... (mungkin ada pengaturan lain di bawah seperti STATIC_URL) ...

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static", 
    # Mungkin ada path lain
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL tujuan setelah user berhasil login
LOGIN_REDIRECT_URL = '/' # Arahkan ke homepage

# URL halaman login (jika user belum login & coba akses halaman terproteksi)
LOGIN_URL = '/accounts/login/'

MEDIA_URL = '/media/'  # URL publik untuk mengakses file media
MEDIA_ROOT = BASE_DIR / 'media' 

CKEDITOR_UPLOAD_PATH = "uploads/" 
CKEDITOR_BROWSE_SHOW_DIRS = True # Opsional: Tampilkan direktori di browser file CKEditor
CKEDITOR_ALLOW_NONIMAGE_FILES = False # Opsional: Hanya izinkan upload gambar (True jika ingin file lain)

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        # --- Gunakan Toolbar Kustom Eksplisit ---
        'toolbar_Custom': [
            {'name': 'document', 'items': ['Source']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            '/', # Pindah baris toolbar
            {'name': 'basicstyles', 'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph', 'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            # --- Pastikan 'Image' ada di sini ---
            {'name': 'insert', 'items': ['Image', 'Table', 'HorizontalRule', 'SpecialChar']}, 
            '/', # Pindah baris toolbar
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
        ],
        'toolbar': 'Custom', # Gunakan toolbar kustom yang baru didefinisikan
        # --- Akhir Definisi Toolbar ---
        'height': 300,
        'width': '100%',
        'tabSpaces': 4,
        'filebrowserUploadUrl': reverse_lazy('ckeditor_upload'),
        'filebrowserBrowseUrl': reverse_lazy('ckeditor_browse'),
        # Coba tanpa extraPlugins dulu, uploadimage biasanya terintegrasi via filebrowser
        # 'extraPlugins': ','.join(['uploadimage']), 
        'removePlugins': 'exportpdf', # Tetap nonaktifkan exportpdf
    },
}
