# Generated by Django 5.2 on 2025-04-10 18:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Teks Pertanyaan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan Pertanyaan dalam Kuis')),
            ],
            options={
                'verbose_name': 'Pertanyaan',
                'verbose_name_plural': 'Pertanyaan',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Teks Pilihan Jawaban')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Apakah Jawaban Benar?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.question', verbose_name='Pertanyaan Terkait')),
            ],
            options={
                'verbose_name': 'Pilihan Jawaban',
                'verbose_name_plural': 'Pilihan Jawaban',
                'ordering': ['question', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Kuis')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi Kuis')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan Kuis dalam Topik')),
                ('pass_mark', models.PositiveSmallIntegerField(default=80, help_text='Nilai minimal (persen) untuk lulus kuis.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nilai Lulus (%)')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='learning.topic', verbose_name='Topik Terkait')),
            ],
            options={
                'verbose_name': 'Kuis',
                'verbose_name_plural': 'Kuis',
                'ordering': ['topic', 'order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.quiz', verbose_name='Kuis Terkait'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Skor (%)')),
                ('passed', models.BooleanField(default=False, verbose_name='Lulus?')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Selesai')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.quiz', verbose_name='Kuis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Upaya Kuis Pengguna',
                'verbose_name_plural': 'Upaya Kuis Pengguna',
                'ordering': ['user', 'quiz', '-completed_at'],
            },
        ),
    ]
