# Generated by Django 5.2 on 2025-04-13 13:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_question_choice_quiz_question_quiz_quizattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Isi Konten Pelajaran'),
        ),
    ]
