# Generated by Django 5.2 on 2025-04-13 15:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_lesson_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Isi Konten Pelajaran'),
        ),
    ]
