# Generated by Django 5.2 on 2025-06-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='minimum_reading_time',
            field=models.PositiveIntegerField(default=5, help_text='Tentukan waktu minimum dalam menit yang dibutuhkan untuk mempelajari pelajaran ini.', verbose_name='Waktu Belajar Minimum (Menit)'),
        ),
    ]
