# Generated by Django 5.2 on 2025-06-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_lesson_minimum_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Batas waktu pengerjaan kuis dalam satuan menit.', verbose_name='Batas Waktu (Menit)'),
        ),
    ]
