# Generated by Django 5.2 on 2025-06-13 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_quiz_time_limit_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='pretest',
            field=models.ForeignKey(blank=True, help_text='Pilih kuis yang akan dijadikan pre-test. Kosongkan jika tidak ada pre-test.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pretest_for_module', to='learning.quiz', verbose_name='Pre-test untuk Modul Ini'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_pretest',
            field=models.BooleanField(default=False, help_text='Centang jika kuis ini dapat digunakan sebagai pre-test untuk sebuah modul.', verbose_name='Jadikan Kuis ini sebagai Pre-test?'),
        ),
        migrations.CreateModel(
            name='PretestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Skor (%)')),
                ('passed', models.BooleanField(default=False, verbose_name='Lulus?')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Selesai')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pretest_attempts_records', to='learning.quiz', verbose_name='Kuis (Pre-test)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pretest_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Upaya Pre-test Pengguna',
                'verbose_name_plural': 'Upaya Pre-test Pengguna',
                'ordering': ['user', 'quiz', '-completed_at'],
            },
        ),
    ]
