# Generated by Django 5.2 on 2025-06-13 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_module_pretest_quiz_is_pretest_pretestattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='pretest',
        ),
        migrations.AddField(
            model_name='topic',
            name='pretest',
            field=models.ForeignKey(blank=True, help_text='Pilih kuis yang akan dijadikan pre-test untuk topik ini.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pretest_for_topic', to='learning.quiz', verbose_name='Pre-test untuk Topik Ini'),
        ),
    ]
